### ISSUE TITLE
[건의] SUAPC standing 관련

### ISSUE THREAD

**Issue by Weaasel** [icpc-sinchon/icpc-sinchon.github.io-old#90]
안녕하세요, 서강대 이윤제입니다.
[SUAPC Standing](https://icpc-sinchon.github.io/suapc)에 팀 솔브수(점수)를 함께 나타내는 것을 건의드립니다.
스탠딩이 더 보기 좋아질 것이라고 생각합니다.
[Sogang ICPC Team 기록](https://acm.sogang.ac.kr/history/)의 형식을 참고했습니다.

**Comment by mori8** [comment]
추가했습니다. 의견 감사합니다 😄
